# Quantum Pipeline

Define small feature map (angle encoding, ZZFeatureMap).

Define variational ansatz (1–3 layers).

Measure expectation values → feature vector.

Train classical classifier on these features.

In [25]:
import pennylane as qml
import pennylane.numpy as np
import pennylane_lightning
from pennylane.optimize import NesterovMomentumOptimizer

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc
# from joblib import Parallel, delayed
import joblib
from multiprocessing import Pool
import itertools
import time
import pandas as pd
# import numpy as np
import os
from dotenv import load_dotenv

# from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit import IBMQ
from qiskit.providers.ibmq import least_busy

In [26]:
data = np.load("data/mnist01_pca4.npz")    #from dataprep notebook

X_train, y_train = data["X_train"], data["y_train"]  
X_test, y_test = data["X_test"], data["y_test"]

#scaling x to fit within [0, π] so the feature map can use meaninful angles instead of angles between [-10,10]
X_max = np.max(np.abs(X_train))
X_train = (np.pi * X_train) / X_max
X_test  = (np.pi * X_test) / X_max


# x = features/ dimensions --> 4
# y = labels
n_qubits=4

#backened 
# dev= qml.device("default.qubit", wires=n_qubits)
dev = qml.device("lightning.qubit", wires=n_qubits)    #faster simulator, uses compiled c++ 


print("PCA reduced shape xtrain:  ", X_train.shape)
print("PCA reduced shape xtest:  ", X_test.shape)
print("ytrain labels: ", y_train.shape)
print("ytest labels: ",y_test.shape)


PCA reduced shape xtrain:   (12665, 4)
PCA reduced shape xtest:   (2115, 4)
ytrain labels:  (12665,)
ytest labels:  (2115,)


## Quantum Feature Map

Classical data is transformed into quantum states. For the main pipeline, I will be using PennyLane as it is easier to build custom circuits and I can compare feature maps in a single framework. Pennylane also supports Qiskit backeneds for a future plugin to run on IBM devices. 


<br>

This is a quantum map $\phi(\mathbf{x})$ from classical feature vector $\mathbf{x}$ to quantum state $|\Phi(\mathbf{x})\rangle\langle\Phi(\mathbf{x})|$ in the Hilbert space, achieved through applying the parameterized unitary operator $\mathcal{U}_{\Phi(\mathbf{x})}$ to the initial state $|0\rangle^{n}$, n being the num of qubits for encoding. This is done so quantum algorithms can use the data. 

Unitary operations are a building block of Qcircuits, where a matrix U is unitary if $$U^\dagger U = U U^\dagger = I$$ 

Some examples are the Pauli X Gate or Hadamard Gate, or in this case, the Rotation Gate $R_y(\theta)$. 
$$
R_y(\theta) = \begin{bmatrix}\cos(\theta/2) & -\sin(\theta/2) \\ \sin(\theta/2) & \cos(\theta/2)\end{bmatrix}, \quad
R_y^\dagger(\theta) = R_y(-\theta), \quad
R_y(\theta) R_y^\dagger(\theta) = I
$$


### ZZ Map Manual - PennyLane

For a ZZ Feature Map, PennyLane does not already have a built in function so we have to do it manually using Hadamard gates, along wiht RZ and ZZ rotations for each qubit pair. This just makes it simpler to integrate over the course of this project. The Qiskit version of this gate is shown in my quantum testing ground. 

Also, out of all encoding methods I could've picked, Angle Encoding seemed to be the most simple and effective when working with circuits (perfect when I am working on a simple project).

The ZZ feature map is a version of the Pauli feature map, which includes entangling gates (ZZ interactions thorugh controlled-phase gates), done after initial data encoding rotations. This is done to allow feature map to capture any potential correlations between features and then maps the data to a more complex hilbert space. 

There are layers of Hadamard gates, single qubit phase rotations, and 2 qubit controlled phase rotations. 

<br>

Hadamard Gates

Creates equal superposition of either state within a qubit

$$
H = \tfrac{1}{\sqrt{2}}
\begin{pmatrix}
1 & 1 \\[6pt]
1 & -1
\end{pmatrix}
$$

RZ Gates 

Single qubit phase rotation around Z axis, diagonal gate

$$
R_Z(\phi) 
= \exp\!\left(-i \tfrac{\phi}{2} Z\right) 
= 
\begin{pmatrix}
e^{-i\phi/2} & 0 \\[6pt]
0 & e^{\,i\phi/2}
\end{pmatrix}
$$


CNOT Gates

Flips target qubit if control qubit is 1.  --> encodes pairwise correlations

$$
\text{CNOT} = CX =
\begin{pmatrix}
1 & 0 & 0 & 0 \\[6pt]
0 & 1 & 0 & 0 \\[6pt]
0 & 0 & 0 & 1 \\[6pt]
0 & 0 & 1 & 0
\end{pmatrix}
$$

<br>

ZZ Feature Map

Encodes the pairwise correlations between features (by constructing a unitary transformation)

$$
U_{\mathrm{ZZ}}(x) = \exp\left( i \sum_i x_i Z_i + i \sum_{i<j} x_i x_j Z_i Z_j \right)
$$


In [27]:
sample_vec = X_train[0]      #1st of 12665
print("Example feature vector: ", sample_vec)  


Example feature vector:  [-0.7779276  -0.57059664 -0.12868546 -0.11485348]


In [28]:
def zz_feature_map(x, wires, reps=1):      #(classical data vector, qubits in use, number of layers/repititions)
    n_qubits = len(wires)

    for _ in range(reps):
        for i in wires: 
            qml.Hadamard(wires=i)            #hadamard gates, uniform superposition of states --> gives room for inference in future entanglement 

        for i, wire in enumerate(wires):     #single qubit phase rotations (encodes classical data to qubit phases)
            qml.RZ(2*x[i], wires=wire)       #RZ rotation, angle = 2x[i] 

        for i in range(n_qubits-1):                    #ZZ entangling layer for pairs of neighboring qubits/wires
            qml.CNOT(wires=[wires[i], wires[i+1]])
            qml.RZ(2*x[i]*x[i+1], wires=wires[i+1])    #performs rotation around Z axis by given amount (angle = 2x[i] * x[i+1]) ENCODES PAIRWISE CORRELATIONS BETWEEN FEATURES x[i] and x[i+1]
            qml.CNOT(wires=[wires[i], wires[i+1]])     #uncomputes entanglement (so final effect is ZZ interaction)


# he
@qml.qnode(dev)
def qnode_measure(x):
    zz_feature_map(x, wires=range(4), reps=1)
    return qml.state()


print(f"ZZFeatureMap state vector: \n {qnode_measure(sample_vec)} \n") 
print(qml.draw(qnode_measure, level='device')(sample_vec))    


ZZFeatureMap state vector: 
 [ 0.12222394+0.21808555j  0.16314236+0.18943223j  0.1394597 +0.20748733j
  0.18799265+0.16479916j  0.14472847+0.20384717j  0.18236686+0.17100389j
  0.2092889 +0.1367412j   0.2373507 +0.07851525j  0.23104784+0.09548243j
  0.24541871+0.04764094j  0.23801256+0.07648543j  0.24966647+0.01290938j
  0.02012213-0.24918888j -0.02982166-0.24821496j -0.07246733-0.23926656j
 -0.13138659-0.21269124j] 

0: ──H──RZ(-1.56)─╭●───────────╭●─────────────────────────────────┤ ╭State
1: ──H──RZ(-1.14)─╰X──RZ(0.89)─╰X─╭●───────────╭●─────────────────┤ ├State
2: ──H──RZ(-0.26)─────────────────╰X──RZ(0.15)─╰X─╭●───────────╭●─┤ ├State
3: ──H──RZ(-0.23)─────────────────────────────────╰X──RZ(0.03)─╰X─┤ ╰State


In this circuit, you can see how each qubit has a Hadamard gate applied (without this, qubits starting in |0⟩ and RZ would only add a global phase - unobservable, as RZ works with relative phase differences between |0⟩ and |1⟩). 

Then, a phase rotation of (x) amount around the Z axis to encode the classical features x[i] as a Z axis phase shift of angle 2x[i].  

Finally, we have the entanglement layers that work through each adjacent pair of qubits to perform phase shifts. Applies controlled phase depending on both qubits and encodes pairwaise correlations into the state. 

**Creates a nonlienar feature map in Hilbert space.**

A CNOT sandwich, which is seen within the multiqubit entanglement layer above, allows for conditional application of a targets rotation, depending on the control qubit. So, in the end, we are maintaining the computational values of the qubit but keeping the phase entanglement of the qubits (it would look the same on the 0,1 level but now hidden quantum phase correlations encode the data)

## Variational Ansatz 

Ansatz: basic architecture of circuit, set of gates that act on specific subsystems with a few assumptions about the appropriate training circuit. Can be generic/problem neutral (hardware ansatz) or can be problem specific. 

Quantum Ansatz: Parameterized Quantum Circuit (PQC) that represents a family of possible quantum stats that are controlled by tunable paramters (normally angles)

$$
|\psi(\theta)\rangle = U(\theta) |0\rangle
$$

ansatz circuit: $$U(\theta)$$ parameters: $$\theta = [\theta_1, \theta_2, \ldots]$$ 


Method used to approimate ground state (lowest energy eingenstate) of quantum system by selecting a trial wavefunction with adjustable parameters. The expectation value of the energy will always be >= to the true ground state energy, so if we optimize the trial wavefunction, we can minimize the expectation value. Built from rotation gates (paramterized by angles) and entangling gates --> these form a layer, we can form many and stakc them to increase expresssiveness. 

**Analogy to CC**

Similar to how a NN layer has weights = rotational angles in the quantum gates. 
- training adjusts the angles to minimize some error/loss 
- patterns to how the gates connect = circuits architecture 

Also similar to deeper NN layers, we can stack them to increase expressiveness


In [29]:
def var_ansatz(params): #params = layers, n_qubits, 3 
    for l in range(params.shape[0]):     #loops through all layers
        for i in range(n_qubits):     #single qubit rotations 
            qml.Rot(params[l,i,0], params[l,i,1], params[l,i,2], wires=i)     # paramertized rotations
        
        for i in range(n_qubits-1):     #entanglers for non linear relationships 
            qml.CNOT(wires=[i, i+1])     #[i:control, i+1:target]


#intial params tensors - random, will be trained in ansatz 
params = np.random.randn(2, n_qubits, 3)     # 2 layers, n_qubits =4, 3 euler angles for each rotation axis 

@qml.qnode(dev)
def ansatz_preview(params):
    var_ansatz(params)
    return qml.state()

print(qml.draw(ansatz_preview)(params))



0: ──Rot(-1.01,1.08,0.93)─╭●──Rot(1.32,-0.75,1.99)───────────────────────╭●──────────────────── ···
1: ──Rot(-1.76,0.41,0.28)─╰X─╭●─────────────────────Rot(0.93,1.52,-0.33)─╰X──────────────────── ···
2: ──Rot(-1.36,0.06,0.93)────╰X────────────────────╭●─────────────────────Rot(1.14,-2.40,-1.00) ···
3: ──Rot(-1.32,1.13,0.42)──────────────────────────╰X─────────────────────Rot(1.86,0.56,-0.11)─ ···

0: ··· ───────┤  State
1: ··· ─╭●────┤  State
2: ··· ─╰X─╭●─┤  State
3: ··· ────╰X─┤  State


This shows rotation gates on each qubit [0..3], with 3 values inside the parenthesis to represent the 3 euler angles used for the rotation (qml.Rot(θ, φ, λ)). The entanglers (CNOT gates) are the vertical lines and dot connecting the qubits. For instance, the dot on qubit 0 indicates that it is the control and the target is qubit 1. There are 6 CNOT gates (3 per layer), with rotations done on each qubit before applying CNOT gates. 

## Measure Expectation Value

In [30]:
@qml.qnode(dev, diff_method="parameter-shift")      #alllows for batches 
def qnode_measure(x, params):
    # x_batch = np.atleast_2d(x_batch)   #ensures shape [batch,featues]       
    zz_feature_map(x, wires=range(4), reps=1)              #encodes data
    var_ansatz(params)       #transforms encoded state w var ansatz
    #returns expectation values  - explicitly 
    return (
        qml.expval(qml.PauliZ(0)),
        qml.expval(qml.PauliZ(1)),
        qml.expval(qml.PauliZ(2)),
        qml.expval(qml.PauliZ(3)),
    )




def get_quantum_features(X, params):
    feats = []
    for x in X:
        feats.append(qnode_measure(x,params))
    # np.array([qnode_measure(x,params) for x in X])
    return feats           #shape [N,n_qubits]

In [31]:
print(qml.draw(qnode_measure)(sample_vec, params))      #now displays zzfeature map  and var ansatz

0: ──H──RZ(-1.56)─╭●───────────╭●──Rot(-1.01,1.08,0.93)─────────────────────────────────── ···
1: ──H──RZ(-1.14)─╰X──RZ(0.89)─╰X─╭●──────────────────────────────╭●──Rot(-1.76,0.41,0.28) ···
2: ──H──RZ(-0.26)─────────────────╰X─────────────────────RZ(0.15)─╰X─╭●─────────────────── ···
3: ──H──RZ(-0.23)────────────────────────────────────────────────────╰X─────────────────── ···

0: ··· ─╭●─────────Rot(1.32,-0.75,1.99)─────────────────────────────────────────────── ···
1: ··· ─╰X────────────────────────────────────────────────────╭●──Rot(0.93,1.52,-0.33) ···
2: ··· ───────────╭●─────────────────────Rot(-1.36,0.06,0.93)─╰X─╭●─────────────────── ···
3: ··· ──RZ(0.03)─╰X─────────────────────Rot(-1.32,1.13,0.42)────╰X─────────────────── ···

0: ··· ─╭●───────────────────────────┤  <Z>
1: ··· ─╰X─────────────────────╭●────┤  <Z>
2: ··· ──Rot(1.14,-2.40,-1.00)─╰X─╭●─┤  <Z>
3: ··· ──Rot(1.86,0.56,-0.11)─────╰X─┤  <Z>


Here you can see the original ZZ featuremap applied to the qubits: each one has a Hadamard gate for placing them into superpositions, then an RZ gate to rotate the qubits around the Z axis by an angle proportionate to its xi value (encodes the data into it's phase), then uses CNOT entanglers and RZ gates to connect qubits. 

The second layer is the Variational Ansatz, where the rotation gates (with the 3 angles) allow for any single-qubit rotation in the bloch sphere, which makes it possible for the ansatz to explore all possible states. 

The final measurement for each qubit is <Z>, which is the measured expectation value of PauliZ operator on each qubit. They then become a classical feature vector we input into the classic models. 

In [32]:
outputs = np.array([qnode_measure(x, params) for x in X_train[:10]])
print(outputs)

[[-0.05542311  0.12282749 -0.02558066  0.12903126]
 [-0.39109101 -0.01037823  0.48454387 -0.09493888]
 [-0.89849611  0.00186577 -0.68129075 -0.15707027]
 [-0.87754521 -0.0553903  -0.76081941 -0.16350736]
 [-0.89168076 -0.09641067 -0.75790464 -0.18599131]
 [-0.00249898  0.24554125  0.08487245  0.20121097]
 [-0.42904186 -0.02578298  0.48999132 -0.11517594]
 [-0.52342689 -0.3980743  -0.15548779 -0.38940268]
 [-0.28369506  0.34736765  0.26455546 -0.06946016]
 [-0.08242832  0.44692402 -0.04262702 -0.05498873]]


### Training Params



This trains the parameters using the variational ansatz and uses a gradient descent optimizer to help train/optimize the params over 20 epochs (using a MSE loss function). 

This block of code runs for several hours, so I have it save the results to the folder /notebooks/params. The bottom of the code (training loop) will be commented out so it will not run each time. 

We use Mean Squared Error (MSE) cost function, which allows us to see if the parameters are a better (closer) fit than randomly assigned parameters. 

In [ ]:
opt = qml.GradientDescentOptimizer(stepsize=0.1)    #tweaks params to minimize cost function
subset = 500  

for i in range(2,5):   # 2-4 qubit circuits 
    print(f"\nTraining {i} qubit circuit")

    dev = qml.device("default.qubit", wires=i, shots=None)
    @qml.qnode(dev)
    def qnode_measure(x, params):
        zz_feature_map(x, wires=range(i), reps=depth)
        var_ansatz(params)  # your variational ansatz should match i qubits
        return [qml.expval(qml.PauliZ(j)) for j in range(i)]

    params = np.random.randn(depth, i, 3)

    # defining a cost function - MSE 
    def cost(params, X, y):         #params (layers, nqubits, 3 euler angles), x=classical data [N, nfeatures], y=labels (0 or 1)
        preds = np.array([qnode_measure(x, params) for x in X])   #for each x, runs zzmap, var ansatz, returns expect value of Z for qubit - [N, nfeatures]
        #loss function
        return np.mean((preds[:,0] - y)**2)  # MSE betwen predicted quantum expect values and classic labels y





    #training loop
    for epoch in range(20):        #optimizes over 50 iterations 
        idx = np.random.permutation(len(X_train))     #ensures we train on different subsets each time
        X_shuffled, y_shuffled = X_train[idx], y_train[idx]

        params = opt.step(lambda p: cost(p, X_shuffled[:subset], y_shuffled[:subset]), params)   #we try to reduce cost while updating params each step 
        cost_val = cost(params, X_train[:subset], y_train[:subset])

        print(f"Epoch: {epoch}, Cost: {cost_val}")


    np.save(f"params/trained_params_{i}.npy", params)    #saves trained numpy array of params to params folder
    print(qml.draw(ansatz_preview)(params))   #recheck 


Epoch: 0, Cost: 1.3029188950097748
Epoch: 1, Cost: 1.1217365216933508
Epoch: 2, Cost: 0.9327088351282316
Epoch: 3, Cost: 0.7537531049972223
Epoch: 4, Cost: 0.5999955547981578
Epoch: 5, Cost: 0.47824424547546496
Epoch: 6, Cost: 0.3871421743317791
Epoch: 7, Cost: 0.32103373939994617
Epoch: 8, Cost: 0.273544381386139
Epoch: 9, Cost: 0.2393129899201396
Epoch: 10, Cost: 0.2143632567901394
Epoch: 11, Cost: 0.19590794074698348
Epoch: 12, Cost: 0.1820350513458083
Epoch: 13, Cost: 0.17143713985809483
Epoch: 14, Cost: 0.16321427656139384
Epoch: 15, Cost: 0.15673989768775234
Epoch: 16, Cost: 0.15157176238735764
Epoch: 17, Cost: 0.14739320114617666
Epoch: 18, Cost: 0.14397419187378846
Epoch: 19, Cost: 0.1411453308057926
0: ──Rot(-0.55,0.59,0.85)──╭●──Rot(1.24,-1.37,1.99)───────────────────────╭●──────────────────── ···
1: ──Rot(-2.45,0.30,-0.48)─╰X─╭●─────────────────────Rot(0.93,1.52,-0.33)─╰X──────────────────── ···
2: ──Rot(-1.36,0.06,0.93)─────╰X────────────────────╭●─────────────────────Rot(1

## Training Model (Classical Classifiers)

### Logistic Regression

In [ ]:
params = np.load("params/trained_params_2.npy")
#expectation values are treated like classical features 
Xq_train = get_quantum_features(X_train, params)     
Xq_test = get_quantum_features(X_test, params)

q_lg_clf = LogisticRegression().fit(Xq_train, y_train)
q_lg_y_pred = q_lg_clf.predict(Xq_test)  

print("Quantum-feature accuracy:", q_lg_clf.score(Xq_test, y_test))
print("\n\nConfusion Matrix: \n", confusion_matrix(y_test, q_lg_y_pred))    
print("\nClassification Report:\n", classification_report(y_test, q_lg_y_pred))

Quantum-feature accuracy: 0.9300236406619385


Confusion Matrix: 
 [[ 889   91]
 [  57 1078]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.91      0.92       980
           1       0.92      0.95      0.94      1135

    accuracy                           0.93      2115
   macro avg       0.93      0.93      0.93      2115
weighted avg       0.93      0.93      0.93      2115



### SVM

In [35]:
q_svm_clf = SVC(kernel='linear', C=1.0, random_state=42)
q_svm_clf.fit(Xq_train, y_train)   

q_svm_y_pred = q_svm_clf.predict(Xq_test)  

print("Quantum-feature accuracy:", q_svm_clf.score(Xq_test, y_test))
print("\n\nConfusion Matrix: \n", confusion_matrix(y_test, q_svm_y_pred))    
print("\nClassification Report:\n", classification_report(y_test, q_svm_y_pred))

Quantum-feature accuracy: 0.9356973995271868


Confusion Matrix: 
 [[ 905   75]
 [  61 1074]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93       980
           1       0.93      0.95      0.94      1135

    accuracy                           0.94      2115
   macro avg       0.94      0.93      0.94      2115
weighted avg       0.94      0.94      0.94      2115



### Save Models

In [36]:
joblib.dump(q_lg_clf, "../results/models/quantum_logreg.pkl")
joblib.dump(q_svm_clf, "../results/models/quantum_svm.pkl")

['../results/models/quantum_svm.pkl']

## Experiments 

### Load IBM account

This section of the code cannot run on IE University wifi, as their network (Cisco Umbrella) blocks all outbound DNS. Since we cannot connect to this on university wifi, we will only run noise as 'False' for error free runs. 

In [37]:
import requests, certifi

print("Using cert file:", certifi.where())

try:
    r = requests.get("https://auth.quantum-computing.ibm.com/api/version", verify=certifi.where())
    print("Response:", r.text)
except Exception as e:
    print("Error:", e)


Using cert file: c:\Users\annap\miniconda3\envs\qfm-env\lib\site-packages\certifi\cacert.pem
Error: HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017690A3D3F0>: Failed to resolve 'auth.quantum-computing.ibm.com' ([Errno 11001] getaddrinfo failed)"))


In [38]:
requests.get("https://auth.quantum-computing.ibm.com/api/version")

ConnectionError: HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017690D70340>: Failed to resolve 'auth.quantum-computing.ibm.com' ([Errno 11001] getaddrinfo failed)"))

In [ ]:
load_dotenv()  
api_key = os.getenv("IBM_API_KEY")
IBMQ.save_account("api_key")      #run only once
IBMQ.load_account()

provider = IBMQ.get_provider(hub='ibm-q')
backend = least_busy(provider.backends(filters=lambda b: b.configuration().n_qubits >= n_qubits and
                                                  not b.configuration().simulator and
                                                  b.status().operational==True))  

print("Using IBM backend:", backend.name())


### Sweep Qubits (Circuit Hyperparameters)

Looping over a range of circuit hyperparamters (number of qubits, depth (# of layers in var. ansatz), shot (# of times qcircuit is sampled), noise (whether to stimulate device noise - will run on IBM)). 

- More qubits would mean a richer feature space but more noise/cost. 
- More depth/layers would mean higher expressivity but is more difficult to train
- More shots means lower measurement noise but a longer runtime
- More noise means noise realism tradeoff


In [39]:
params = np.load("params/trained_params.npy")      #trained parameters
 
#trained models
q_lg_clf = joblib.load("../results/models/quantum_logreg.pkl")
q_svm_clf = joblib.load("../results/models/quantum_svm.pkl")   


In [ ]:
n_qubit_list = [2,3,4]
depth_list = [1,2]
shot_list= [None, 1024]      #none means no sampling - analytic
noise_list = [False, True]    #true = use simulator 

In [ ]:
lg_results = []
svm_results = []   

for n_qubits, depth, shots, noise in itertools.product(n_qubit_list, depth_list, shot_list, noise_list):
    params_path = f"params/trained_params_{n_qubits}.npy"       #loads correct params file for qubits
    params = np.load(params_path)
    
    #adjust device configration
    if noise:
        dev =  qml.device("qiskit.ibmq", wires=n_qubits, backend=backend, shots=shots)     #now runs on ibm hardware    
    else:
        dev = qml.device("default.qubit", wires=n_qubits, shots=shots)


    @qml.qnode(dev)
    def qnode_measure(x, params):
        zz_feature_map(x, wires=range(n_qubits), reps=depth)
        var_ansatz(params)
        return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]

    #extract quantum features
    Xq_train = get_quantum_features(X_train, params)
    Xq_test = get_quantum_features(X_test, params)
    # print(f"DEBUG: {Xq_train.mean()}, {Xq_train.std()}")


    q_lr_start = time.time()
    #log reg 
    q_lg_clf = LogisticRegression()
    q_lg_clf.fit(Xq_train, y_train)
    q_lg_y_pred = q_lg_clf.predict(Xq_test)
    q_lg_acc = np.mean(q_lg_y_pred == y_test)
    q_lr_runtime = (time.time()- q_lr_start, 3)


    #svm model 
    q_svm_start = time.time()
    q_svm_clf = SVC(kernel='linear', C=1.0, random_state=42)
    q_svm_clf.fit(Xq_train, y_train)
    q_svm_y_pred = q_svm_clf.predict(Xq_test)   
    q_svm_acc = np.mean(q_svm_y_pred == y_test)
    q_svm_runtime = (time.time()-q_svm_start, 3)

    lg_results.append({
        "n_qubits": n_qubits, 
        "depth": depth,  
        "shots": shots if shots else "analytic", 
        "noise": noise,
        "accuracy": q_lg_acc,
        "runtime_sec": q_lr_runtime
    })    

    svm_results.append({
        "n_qubits": n_qubits,
        "depth": depth,
        "shots": shots if shots else "analytic",
        "noise": noise,   
        "accuracy":q_svm_acc,    
        "runtime_sec": q_svm_runtime   
    })

    print(f"Run ({n_qubits} qubits, depth={depth}, shots={shots}, noise={noise}) = Log reg acc={q_lg_acc:.3f}, SVM acc={q_svm_acc:.3f}")


Run (2 qubits, depth=1, shots=None, noise=False) = Log reg acc=0.899, SVM acc=0.896
Run (2 qubits, depth=1, shots=1024, noise=False) = Log reg acc=0.898, SVM acc=0.897
Run (2 qubits, depth=2, shots=None, noise=False) = Log reg acc=0.776, SVM acc=0.791
Run (2 qubits, depth=2, shots=1024, noise=False) = Log reg acc=0.776, SVM acc=0.786
Run (3 qubits, depth=1, shots=None, noise=False) = Log reg acc=0.922, SVM acc=0.925
Run (3 qubits, depth=1, shots=1024, noise=False) = Log reg acc=0.923, SVM acc=0.926
Run (3 qubits, depth=2, shots=None, noise=False) = Log reg acc=0.789, SVM acc=0.796
Run (3 qubits, depth=2, shots=1024, noise=False) = Log reg acc=0.790, SVM acc=0.798
Run (4 qubits, depth=1, shots=None, noise=False) = Log reg acc=0.930, SVM acc=0.936
Run (4 qubits, depth=1, shots=1024, noise=False) = Log reg acc=0.932, SVM acc=0.933
Run (4 qubits, depth=2, shots=None, noise=False) = Log reg acc=0.866, SVM acc=0.877
Run (4 qubits, depth=2, shots=1024, noise=False) = Log reg acc=0.868, SVM ac

### Save Results

In [47]:
q_lg_df = pd.DataFrame(lg_results)
q_lg_df.to_csv("../results/metrics/q_lr_sweep_results.csv", index=False)
print("\nSaved to results/metrics/q_lr_sweep_results.csv")


q_svm_df = pd.DataFrame(svm_results)
q_svm_df.to_csv("../results/metrics/q_svm_sweep_results.csv", index=False)
print("\nSaved to results/metrics/q_svm_sweep_results.csv")


Saved to results/metrics/q_lr_sweep_results.csv

Saved to results/metrics/q_svm_sweep_results.csv
